### PR TITLE
Switch CNI to Cilium

### PR DESCRIPTION
**Pull request by klausenbusk**
This adds the missing pieces for using Cilium as CNI, which we
have switched to[1][2][3].

[1] https://github.com/distributed-technologies/helm-charts/pull/224
[2] https://github.com/distributed-technologies/helm-charts/pull/229
[3] https://github.com/distributed-technologies/yggdrasil/pull/61

- [x] The new functionality was tested
- [x] The tests were executed with `bitbake mukube-test-image -c testimage` and they all succeeded
- [x] The new code was sufficiently documented

### CODE REVIEW

**Comment by klausenbusk** [comment]
Tests are green:
```
RESULTS:
RESULTS - bootservice.BootServiceTest.test_boot_service: PASSED (0.48s)
RESULTS - config.ConfigPartitionTest.test_config_present: PASSED (0.09s)
RESULTS - kubeadm.KubeadmInitTest.test_kubeadm_init: PASSED (44.31s)
SUMMARY:
mukube-test-image () - Ran 3 tests in 44.881s
mukube-test-image - OK - All required tests passed (successes=3, skipped=0, failures=0, errors=0)
```

**Comment by klausenbusk** [comment]
It isn't happy without internet, hmm:
```
  Normal   Scheduled  44s   default-scheduler  Successfully assigned yggdrasil/cilium-kh497 to master0
  Normal   Pulling    43s   kubelet            Pulling image "quay.io/cilium/cilium:v1.11.1@sha256:251ff274acf22fd2067b29a31e9fda94253d2961c061577203621583d7e85bd2"
  Warning  Failed     14s   kubelet            Failed to pull image "quay.io/cilium/cilium:v1.11.1@sha256:251ff274acf22fd2067b29a31e9fda94253d2961c061577203621583d7e85bd2": rpc error: code = Unknown desc = pinging container registry quay.io: Get "https://quay.io/v2/": dial tcp: lookup quay.io: Temporary failure in name resolution
  Warning  Failed     14s   kubelet            Error: ErrImagePull
  Normal   BackOff    14s   kubelet            Back-off pulling image "quay.io/cilium/cilium:v1.11.1@sha256:251ff274acf22fd2067b29a31e9fda94253d2961c061577203621583d7e85bd2"
  Warning  Failed     14s   kubelet            Error: ImagePullBackOff
```

**Comment by skovbakke** [comment]
> It isn't happy without internet, hmm (likely due to the usage of both a tag and digest):
> 
> ```
>   Normal   Scheduled  44s   default-scheduler  Successfully assigned yggdrasil/cilium-kh497 to master0
>   Normal   Pulling    43s   kubelet            Pulling image "quay.io/cilium/cilium:v1.11.1@sha256:251ff274acf22fd2067b29a31e9fda94253d2961c061577203621583d7e85bd2"
>   Warning  Failed     14s   kubelet            Failed to pull image "quay.io/cilium/cilium:v1.11.1@sha256:251ff274acf22fd2067b29a31e9fda94253d2961c061577203621583d7e85bd2": rpc error: code = Unknown desc = pinging container registry quay.io: Get "https://quay.io/v2/": dial tcp: lookup quay.io: Temporary failure in name resolution
>   Warning  Failed     14s   kubelet            Error: ErrImagePull
>   Normal   BackOff    14s   kubelet            Back-off pulling image "quay.io/cilium/cilium:v1.11.1@sha256:251ff274acf22fd2067b29a31e9fda94253d2961c061577203621583d7e85bd2"
>   Warning  Failed     14s   kubelet            Error: ImagePullBackOff
> ```

The deault value for [`useDigest`](https://github.com/cilium/cilium/blob/76d34dbdfc1bf14cb8976a86ccf1e98dae6d72c5/install/kubernetes/cilium/values.yaml#L89) is false, and this sets the [`cilium.image`](https://github.com/cilium/cilium/blob/76d34dbdfc1bf14cb8976a86ccf1e98dae6d72c5/install/kubernetes/cilium/templates/_helpers.tpl#L21) without the digest. However, in the released chart, the `useDigest` is changed to `true` and the `digest` is specified.  We can override the values in the values file in nidhogg [like this](https://github.com/distributed-technologies/yggdrasil/commit/7d23e0c62b43fa8b657ef2c75525cc4b0ae7544b). 

```
  Normal   Scheduled  6m5s                  default-scheduler  Successfully assigned yggdrasil/cilium-d4bcb to master0
  Normal   Pulled     6m5s                  kubelet            Container image "quay.io/cilium/cilium:v1.11.1" already present on machine
```

**Review by skovbakke — APPROVED** [review]
The above mentioned issues are not really related to mukube. This seems to work.
LGTM 🥳

**Review by jacobcrawford — APPROVED** [review]
I have tested the changes and it works.

**Pull request merged**
